#!/bin/bash

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

export CONFIG_DIR="$HOME/.config/sketchybar"
export ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
export PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

export FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
export PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
cd "$HOME/.config/sketchybar/helper" && make
"$HOME/.config/sketchybar/helper/helper" "$HELPER" > /dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  height=35
  color=$TRANSPARENT
  shadow=on
  position=top
  sticky=on
  # padding_right=10
  # padding_left=10
  corner_radius=0
  y_offset=0
  # margin=10
  blur_radius=20
  notch_width=0
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=30
  background.corner_radius=9
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center
source "$ITEM_DIR/apple_music.sh"

# Right
source "$ITEM_DIR/calendar.sh"

sketchybar --add alias "TextInputMenuAgent,Item-0" right \
    --set "TextInputMenuAgent,Item-0" padding_left=0 padding_right=0 label.width=0 update_freq=1

source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/bluetooth.sh"
source "$ITEM_DIR/activity.sh"
source "$ITEM_DIR/tailscale.sh"
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

# Disable hotloading to avoid automatic full reloads while plugins update state
sketchybar --hotload false #fix

echo "sketchybar configuration loaded.."
